name: flutter_login_types
description: Login with BLoC architecture

version: 1.0.0+1

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  auth0_flutter: ^1.14.0
  collection: ^1.19.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_appauth: ^11.0.0
  flutter_facebook_auth: ^7.1.5
  flutter_hooks: ^0.21.3+1
  flutter_local_notifications: ^20.1.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  formz: ^0.8.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^17.0.1
  go_router_paths: ^0.2.2
  google_fonts: ^8.0.1
  google_sign_in: ^7.2.0
  hooks_riverpod: ^3.2.0
  intl: ^0.20.2
  local_auth: ^3.0.1
  pinput: ^6.0.1
  shared_preferences: ^2.5.4
  sign_in_with_apple: ^7.0.1
  twitter_login: ^4.4.2
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.11.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
  generate: true
